import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {sourceVersion} from '../scripts/build-version.mjs';
const dir=await mkdtemp(join(tmpdir(),'lp-owner-'));
await build({entryPoints:['src/index.ts','src/owner-auth.ts','src/version.ts'],outdir:dir,bundle:true,platform:'node',format:'esm',mainFields:['main'],banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outExtension:{'.js':'.mjs'}});
const {default:worker}=await import(join(dir,'index.mjs')),{ownerRouteProtected,ownerAuthenticated,ownerGuard}=await import(join(dir,'owner-auth.mjs'));
const origin='https://terminal.test',fixtureKey='synthetic-owner-key-not-a-secret',store=new Map();let reads=0,writes=0,providerCalls=0;
const kv={get:async k=>{reads++;return store.has(k)?JSON.parse(store.get(k)):null;},put:async(k,v)=>{writes++;store.set(k,v);},delete:async k=>store.delete(k)},env={LP_CACHE:kv,TX_KEY:fixtureKey,WALLETS:'',MIN_TVL_USD:'5000'},req=(path,options={})=>new Request(origin+path,options);
const protectedPaths=['/api/solana/send','/api/evm/send','/api/paybox/status','/api/paybox/callback?code=fixture&state=fixture','/api/paybox/connect','/api/paybox/mcp','/api/paybox/recover','/api/paybox/disconnect','/api/solana/preview','/api/solana/owned','/api/solana/status','/api/evm/preview','/api/evm/status','/api/tx/plan','/api/x/fixture/positions','/api/debug/meteora-pnl/fixture','/api/paper-fleet/control','/api/paper-lab/control','/api/bot/control','/api/active-lp/control','/api/scanner/control'];
const publicReadPaths=['/api/positions','/api/history','/api/wallet-intelligence','/api/position-break-even','/api/position-chart','/api/exit-preview','/api/check','/api/range-alerts','/api/volume-alerts','/api/data-budget','/paper-research.json','/media/pat-lp-replay-v2.mp4','/media/replay-poster.png'];
const originalFetch=globalThis.fetch,originalNow=Date.now;globalThis.fetch=async()=>{providerCalls++;throw Error('No provider or financial operation may run in auth fixtures');};
try{
 for(const path of [...protectedPaths,'/api/%70aybox/status'])for(const method of ['GET','HEAD','POST']){const before=reads,r=await worker.fetch(req(path,{method}),env);assert.equal(r.status,401,method+' '+path+' requires owner authentication');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(reads,before,'Unauthorized routes stop before private KV/provider access');assert.ok(ownerRouteProtected(new URL(origin+path).pathname,method));}
 for(const path of [...publicReadPaths,'/%70aper-research.json','/paper-research%2Ejson','/media/%70at-lp-replay-v2.mp4']){
  for(const method of ['GET','HEAD'])assert.equal(ownerRouteProtected(path,method),false,method+' '+path+' is public to read');
  for(const method of ['POST','PUT','DELETE']){assert.equal(ownerRouteProtected(path,method),true,method+' '+path+' still requires owner authentication');const before=reads,r=await worker.fetch(req(path,{method,headers:{origin}}),env);assert.equal(r.status,401);assert.equal(reads,before,'Public read access cannot bypass the mutation guard');}
 }
 for(const path of ['/api/solana/send','/api/evm/send','/api/paybox/status']){const before=reads,r=await worker.fetch(req(path,{method:'POST',headers:{'x-terminal-key':fixtureKey,origin}}),{...env,TX_KEY:undefined});assert.equal(r.status,401,'No secret never permits owner mutation access');assert.equal(reads,before);}
 assert.equal(ownerRouteProtected('/api/refresh','POST'),false,'The normal data refresh button works without owner login');for(const method of ['GET','HEAD','PUT','DELETE'])assert.equal(ownerRouteProtected('/api/refresh',method),true,'Refresh only permits a same-origin POST');
 for(const refreshOrigin of [undefined,'https://evil.test'])for(const refreshEnv of [env,{...env,TX_KEY:undefined}]){const before=reads,r=await worker.fetch(req('/api/refresh',{method:'POST',headers:refreshOrigin?{origin:refreshOrigin}:{}}),refreshEnv);assert.equal(r.status,403,'Data refresh rejects missing or foreign Origin');assert.equal(reads,before,'Rejected refresh never reaches cache or provider work');}
 assert.equal(await ownerGuard(req('/api/refresh',{method:'POST',headers:{origin}}),{...env,TX_KEY:undefined}),null,'Same-origin refresh passes the access guard without a password');
 assert.equal(providerCalls,0,'Denied methods never reach a provider or financial operation');
 assert.equal((await worker.fetch(req('/api/paybox/status?key='+fixtureKey),env)).status,401,'Query parameters cannot authenticate');
 assert.equal((await worker.fetch(req('/api/paybox/status',{headers:{cookie:'lp_paybox='+'a'.repeat(43)}}),env)).status,401,'PayBox OAuth does not grant terminal owner access');
 const now=new Date().toISOString(),portfolioEnv={...env,WALLETS:'Research:fixture-wallet'},positionFixture={positions:[{id:'fixture-position',wallet:'Research',chain:'solana'}],balances:[{wallet:'Research',symbol:'SOL',amount:1}],updatedAt:now,sources:{}},closedFixture={wallet:'Research',positionAddress:'fixture-closed',pair:'FIXTURE/SOL',closedAt:now};
 store.set('positions:v1',JSON.stringify(positionFixture));store.set('journey:v1:sol:fixture-wallet',JSON.stringify({readAt:now,attemptAt:now,data:{closed:[closedFixture],totals:{deposits:10,withdrawals:11,fees:1,pnl:1,positions:1},errors:[]}}));
 for(const publicEnv of [portfolioEnv,{...portfolioEnv,TX_KEY:undefined}]){
  const beforeCalls=providerCalls,r=await worker.fetch(req('/api/positions'),publicEnv);assert.equal(r.status,200,'Portfolio opens without a password');assert.deepEqual(await r.json(),positionFixture);
  const history=await worker.fetch(req('/api/history'),publicEnv);assert.equal(history.status,200,'Saved wallet history opens without a password');const saved=await history.json();assert.deepEqual(saved.open,positionFixture.positions);assert.deepEqual(saved.closed,[closedFixture]);assert.equal(saved.totals.Research.pnl,1);assert.equal(providerCalls,beforeCalls,'Cached portfolio reads need no provider work');
 }
 let assetReads=0;for(const method of ['GET','HEAD']){const r=await worker.fetch(req('/paper-research.json',{method}),{...env,TX_KEY:undefined,ASSETS:{fetch:async()=>{assetReads++;return Response.json({unexpected:true});}}});assert.equal(r.status,200,'Research is public '+method);assert.equal(r.headers.get('cache-control'),'no-store');if(method==='HEAD')assert.equal(await r.text(),'');else assert.ok((await r.json()).personal);}
 assert.equal(assetReads,0,'Bundled research is served directly');
 for(const path of ['/media/pat-lp-replay-v2.mp4','/media/replay-poster.png']){const r=await worker.fetch(req(path),{...env,TX_KEY:undefined,ASSETS:{fetch:async()=>{assetReads++;return new Response('fixture replay');}}});assert.equal(r.status,200,'Replay is public');assert.equal(await r.text(),'fixture replay');}assert.equal(assetReads,2);
 const status=await worker.fetch(req('/api/auth/status'),env);assert.deepEqual(await status.json(),{authenticated:false});
 for(const path of ['/api/pools','/api/stats','/api/research/pools','/api/paper-fleet','/api/paper-lab','/api/bot','/api/active-lp'])assert.equal(ownerRouteProtected(path),false,'Public catalogue and synthetic results remain public');
 let staticReads=0;assert.equal((await worker.fetch(req('/owner-access.js'),{...env,ASSETS:{fetch:async()=>{staticReads++;return new Response('public');}}})).status,200);assert.equal(staticReads,1,'Public static assets bypass provider work after the owner guard');
 const login=(key=fixtureKey,site=origin)=>worker.fetch(req('/api/auth/login',{method:'POST',headers:{origin:site,'content-type':'application/json'},body:JSON.stringify({key})}),env);
 assert.equal((await login(fixtureKey,'https://evil.test')).status,403);assert.equal((await login('incorrect')).status,401);
 let r=await login();assert.equal(r.status,200);const text=await r.text();assert.doesNotMatch(text,new RegExp(fixtureKey));const setCookie=r.headers.get('set-cookie');assert.ok(setCookie.includes('HttpOnly')&&setCookie.includes('Secure')&&setCookie.includes('SameSite=Lax'));const ownerCookie=setCookie.split(';')[0],sessionId=ownerCookie.split('=')[1];assert.match(sessionId,/^[a-f0-9]{64}$/);
 assert.ok(![...store.keys()].some(k=>k.includes(sessionId)),'Session storage hashes the random bearer ID');assert.ok(![...store.values()].some(v=>v.includes(fixtureKey)||v.includes(sessionId)),'No raw owner key or bearer stored');
 const ownerReq=path=>req(path,{headers:{cookie:ownerCookie}});assert.equal(await ownerAuthenticated(ownerReq('/'),env),true);
 assert.equal((await worker.fetch(ownerReq('/api/auth/status'),env)).status,200);assert.equal((await worker.fetch(ownerReq('/api/paybox/status'),env)).status,200);
 assert.equal((await worker.fetch(ownerReq('/api/paybox/callback?code=fixture&state=fixture'),env)).status,400,'Owner cookie allows OAuth callback to reach its own state validation');
 store.set('positions:v1',JSON.stringify({positions:[{id:'private'}],balances:[]}));r=await worker.fetch(ownerReq('/api/positions'),env);assert.equal(r.status,200);assert.equal((await r.json()).positions[0].id,'private');
 assert.equal((await worker.fetch(ownerReq('/api/x/fixture/positions'),env)).status,410,'URL-key aliases stay retired after login');
 assert.equal((await worker.fetch(req('/api/paybox/disconnect',{method:'POST',headers:{cookie:ownerCookie,origin:'https://evil.test'}}),env)).status,403,'Owner cookie does not bypass origin enforcement');
 assert.equal(await ownerAuthenticated(ownerReq('/'),{...env,TX_KEY:'rotated-synthetic-key'}),false,'Changing owner key immediately invalidates session fingerprint');
 Date.now=()=>originalNow()+13*60*60*1000;assert.equal(await ownerAuthenticated(ownerReq('/'),env),false,'Session expires independently of KV cleanup');Date.now=originalNow;
 r=await worker.fetch(req('/api/auth/logout',{method:'POST',headers:{cookie:ownerCookie,origin}}),env);assert.equal(r.status,200);assert.ok(r.headers.get('set-cookie').includes('Max-Age=0'));assert.equal(await ownerAuthenticated(ownerReq('/'),env),false);
 for(let i=0;i<10;i++)assert.equal((await worker.fetch(req('/api/auth/login',{method:'POST',headers:{origin,'cf-connecting-ip':'192.0.2.123'},body:JSON.stringify({key:'wrong'})}),env)).status,401);r=await worker.fetch(req('/api/auth/login',{method:'POST',headers:{origin,'cf-connecting-ip':'192.0.2.123'},body:JSON.stringify({key:fixtureKey})}),env);assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60');
 assert.equal(providerCalls,0,'Public cached reads and denied mutations never invoke financial providers');
 console.log('PASS: public read-only portfolio/research/replay, protected mutations and financial routes, fail-closed configuration, exact owner headers, HttpOnly login, CSRF, OAuth callback, rotation, expiry, logout and bounded login attempts');

 r=await worker.fetch(req('/api/version'),env);assert.equal(r.status,200);let v=await r.json();assert.ok(v.gitSha===null||/^[a-f0-9]{40,64}$/.test(v.gitSha),'A commit is absent or a full real commit ID');assert.match(v.sourceSha,/^[a-f0-9]{64}$/);assert.ok(Number.isFinite(Date.parse(v.buildAt)));assert.equal(v.deployedAt,null);
 const versionId='00000000-0000-4000-8000-000000000001',versionEnv={...env,CF_VERSION_METADATA:{id:versionId,timestamp:'2026-09-30T17:00:00.000Z'}};
 v=await (await worker.fetch(req('/api/version'),versionEnv)).json();assert.equal(v.workerVersionId,versionId);assert.equal(v.versionCreatedAt,'2026-09-30T17:00:00.000Z');assert.equal(v.deployedAt,null,'Version creation is not reported as deployment activation');
 store.set('deploy:version:'+versionId,JSON.stringify({versionId,sourceSha:v.sourceSha,deployedAt:'2026-09-30T17:01:00.000Z'}));v=await (await worker.fetch(req('/api/version'),versionEnv)).json();assert.equal(v.deployedAt,'2026-09-30T17:01:00.000Z');
 store.set('deploy:version:'+versionId,JSON.stringify({versionId,sourceSha:'incorrect',deployedAt:'2026-09-30T17:01:00.000Z'}));assert.equal((await (await worker.fetch(req('/api/version'),versionEnv)).json()).deployedAt,null,'A receipt for other source bytes cannot label this deployment');
 const sourceDir=await mkdtemp(join(tmpdir(),'lp-version-fixture-'));for(const d of ['src','public','scripts','execution'])await mkdir(join(sourceDir,d));await writeFile(join(sourceDir,'src/a.ts'),'export const value=1;');await writeFile(join(sourceDir,'public/index.html'),'<p>fixture</p>');await writeFile(join(sourceDir,'.dev.vars'),'SHOULD_NOT_BE_READ=fixture');
 const a=await sourceVersion(sourceDir,new Date('2026-09-30T10:00:00Z')),b=await sourceVersion(sourceDir,new Date('2026-09-30T11:00:00Z'));assert.equal(a.sourceSha,b.sourceSha);assert.notEqual(a.buildAt,b.buildAt);assert.equal(a.gitSha,null);
 await writeFile(join(sourceDir,'src/build-version.ts'),'generated timestamp changes');await writeFile(join(sourceDir,'.dev.vars'),'changed ignored fixture');assert.equal((await sourceVersion(sourceDir)).sourceSha,a.sourceSha,'Generated metadata and private environment do not affect source identity');
 await writeFile(join(sourceDir,'src/a.ts'),'export const value=2;');assert.notEqual((await sourceVersion(sourceDir)).sourceSha,a.sourceSha,'A real source edit changes fallback identity');
 console.log('PASS: public version, truthful absent Git, deterministic source hashing, real edit detection, secret exclusions and separately recorded deployment time');
}finally{globalThis.fetch=originalFetch;Date.now=originalNow;}
