import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const dir=await mkdtemp(join(tmpdir(),'lp-execution-ui-'));
await build({entryPoints:['execution/composer-state.ts'],outdir:dir,bundle:true,platform:'node',format:'esm',outExtension:{'.js':'.mjs'}});
const state=await import(join(dir,'composer-state.mjs'));
const entries=new Map(),storage={getItem:key=>entries.get(key)||null,setItem:(key,value)=>entries.set(key,String(value)),removeItem:key=>entries.delete(key)};
const c=state.createComposer('pool','solana',{},storage);
assert.equal(c.snapshot().draft.amountSol,'0.5');
c.update({lowerPriceSol:'0.000001',upperPriceSol:'0.000002',strategy:'bid-ask',depositMode:'sol-only'});
const r=c.snapshot().revision;
assert.equal(c.acceptPreview({previewId:'review',expiresAt:1000},r),true);
assert.equal(c.usable(999),true);assert.equal(c.usable(1000),false);
c.update({amountSol:'1'});assert.equal(c.snapshot().review,null);assert.equal(c.acceptPreview({expiresAt:2000},r),false,'late simulation cannot restore an edited review');
c.lock(true);assert.equal(c.update({lowerPriceSol:'9'}),false);assert.equal(c.snapshot().draft.lowerPriceSol,'0.000001');
assert.deepEqual(state.createComposer('pool','solana',{},storage).snapshot().draft,c.snapshot().draft,'reload preserves exact draft, amount, shape and funding');
assert.equal(state.decimalInput('3.145e-8'),'0.00000003145');assert.equal(state.rangeError('2','1'),'The floor must be below the top price.');
const op={pool:'pool',preview:{previewId:'a',expiresAt:100,walletKind:'paybox'}};state.writeOperation(storage,'solana',op);
state.removeOperation(storage,'solana',{previewId:'b'});assert.equal(state.readOperation(storage,'solana').preview.previewId,'a');
assert.equal(state.canResumeInPool(op,'other'),false);assert.equal(state.interruptedAction({...op,requestId:'original'},200),'request');assert.equal(state.interruptedAction({...op,signature:'known'},200),'status');assert.equal(state.interruptedAction(op,100),'expired');
entries.clear();

// Minimal DOM drives the real mounted controllers, with provider/wallet dependencies mocked.
let now=Date.now();const originalDate=Date;class ClockDate extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}globalThis.Date=ClockDate;
const timers=[],documentEvents=[],requests=[];let requestMode='pending',statusMode='none',previewDeferred=null,sendFailure=false;
class Node{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset={};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.children=[];this.parent=null;this.listeners={};this.value=attrs.value||'';this.disabled='disabled'in attrs;this.hidden='hidden'in attrs;this._html='';this._text='';this.connected=false;this.classList={add:()=>{}};}
 get isConnected(){return this.connected||!!this.parent?.isConnected;}
 set innerHTML(html){this._html=html;this._text='';this.children=[];const stack=[this];for(const token of html.match(/<[^>]*>|[^<]+/g)||[]){if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token.startsWith('<')){const m=token.match(/^<([\w-]+)/);if(!m)continue;const attrs={};for(const a of token.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){if(a.index===1)continue;attrs[a[1]]=a[2]??'';}const node=new Node(m[1],attrs);stack.at(-1).append(node);if(!['input','br','hr','img','meta'].includes(m[1]))stack.push(node);}else stack.at(-1)._text+=token;}for(const s of this.querySelectorAll('select'))if(!s.value)s.value=s.querySelector('option')?.attrs.value||'';}
 get innerHTML(){return this._html;}
 get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}set textContent(v){this._text=String(v);this.children=[];this._html='';}
 append(...nodes){for(const node of nodes){node.parent=this;this.children.push(node);}}prepend(node){node.parent=this;this.children.unshift(node);}
 replaceChildren(...nodes){this.children=[];this._html='';this.append(...nodes);}
 insertAdjacentHTML(_where,html){const holder=new Node();holder.innerHTML=html;this.append(...holder.children);}
 setAttribute(key,value){this.attrs[key]=String(value);if(key.startsWith('data-'))this.dataset[key.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(value);}
 matches(selector){const cls=selector.match(/\.([\w-]+)/)?.[1];if(cls&&!(this.attrs.class||'').split(/\s+/).includes(cls))return false;const tag=selector.match(/^[\w-]+/)?.[0];if(tag&&tag.toUpperCase()!==this.tagName)return false;for(const a of selector.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)){if(!(a[1]in this.attrs))return false;if(a[2]!==undefined&&this.attrs[a[1]]!==a[2])return false;}return true;}
 querySelectorAll(selector){const result=[];const parts=selector.split(',').map(s=>s.trim());const visit=node=>{for(const child of node.children){if(parts.some(part=>{const bits=part.split(/\s+/);if(!child.matches(bits.at(-1)))return false;if(bits.length===1)return true;let parent=child.parent;while(parent){if(parent.matches(bits[0]))return true;parent=parent.parent;}return false;}))result.push(child);visit(child);}};visit(this);return result;}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event);return true;}
 focus(){document.activeElement=this;}
}
const roots=[];
globalThis.document={activeElement:null,querySelector:()=>null,createElement:tag=>new Node(tag),addEventListener:(type,fn)=>documentEvents.push([type,fn]),dispatchEvent:event=>{for(const [type,fn]of documentEvents)if(type===event.type)fn(event);return true;}};
globalThis.window={innerHeight:800,addEventListener:()=>{}};globalThis.localStorage=storage;
globalThis.setInterval=(fn,ms)=>{timers.push({fn,ms});return timers.length;};globalThis.clearInterval=()=>{};globalThis.CustomEvent=class{constructor(type,options={}){this.type=type;this.detail=options.detail;}};
const solWallet={id:'sol-wallet',address:'sol-owner',name:'Phone',family:'solana'},evmWallet={id:'evm-wallet',address:'0x'+'11'.repeat(20),name:'Robinhood',family:'evm'};
const solPreview=pool=>({pool,previewId:'sol-review-'+pool,expiresAt:now+75000,lastValidBlockHeight:999,amountSol:'0.5',networkFeeLamports:5000,rentDepositedLamports:1000,postBalanceLamports:1e9,netChangeLamports:-5e8,lowerBin:-10,upperBin:-5,lowerPriceSol:.000001,upperPriceSol:.000002,strategy:'Bid-Ask',depositMode:'sol-only',owner:'sol-owner',position:'position',simulationSlot:10,transactionBase64:'AA==',messageHex:'abcd'});
const evmPreview=(pool,stage='mint')=>({previewId:'evm-review-'+pool,operationId:'evm-op-'+pool,action:'open',stage,chainId:4663,owner:evmWallet.address,credentialId:evmWallet.id,expiresAt:now+75000,transaction:{from:evmWallet.address},transactionJson:'{"exact":"transaction"}',review:{pool,pair:'TEST/WETH',amountEth:'0.006',amountToken:'10',expectedEth:'0.004',expectedToken:'9',maximumGasEth:'0.0001',simulated:{eth:'0.0039',token:'8.9'},range:{priceLowerEth:'0.00001',priceUpperEth:'0.00002',tickLower:-100,tickUpper:100},minimumToken:'2.3'}});
globalThis.__mocks={
 mountPaybox:async()=>{},mountWalletPicker:async(host,family,onChange)=>{host.innerHTML='<select data-credential></select>';onChange(family==='evm'?evmWallet:solWallet);return {selected:()=>family==='evm'?evmWallet:solWallet};},payboxWallet:async options=>options?.family==='evm'?evmWallet:solWallet,payboxReady:async()=>true,
 requestPayboxSignature:async(input,onId)=>{requests.push({sign:input});onId('same-request');if(requestMode==='lost')throw Error('Lost request response');return {input,result:{},id:'same-request'};},payboxResult:async()=>({status:requestMode==='success'?'success':'pending_approval',output:{value:{serializedTransaction:'0xsigned'}}}),signingCard:async()=>{if(requestMode==='pending')throw Error('Card interrupted');},reopenPaybox:async()=>{requests.push({reopen:'same-request'});if(requestMode==='pending')throw Error('Card interrupted');},applyPayboxSignature:()=> 'signed',signedEvmTransaction:()=>({signedTransactionHex:'0xsigned',txHash:'0xhash'})
};
globalThis.fetch=async(path,options)=>{const body=options?.body?JSON.parse(options.body):null;requests.push({path,body});if(path==='/api/solana/preview'){if(previewDeferred)return new Promise(resolve=>previewDeferred.resolve=()=>resolve(Response.json(solPreview(body.pool))));return Response.json(solPreview(body.pool));}if(path==='/api/evm/preview')return Response.json(evmPreview(body.pool,statusMode==='approval-ready'?'mint':'mint'));if(path.startsWith('/api/evm/status')){if(statusMode==='none')return Response.json({status:'none'});if(statusMode==='approval-ready')return Response.json({status:'confirmed',stage:'approval',action:'open',operationId:'existing-approval',preview:evmPreview('evm-pool','approval'),nextReviewRequired:true});if(statusMode==='retry-ready'){const op=state.readOperation(storage,'evm');return Response.json({status:'awaiting-signature',operationId:op.preview.operationId,owner:op.preview.owner,credentialId:op.credentialId,requestId:op.requestId,preview:op.preview,txHash:null});}if(statusMode==='retried')return Response.json({status:'confirmed'});if(statusMode==='discovered')return Response.json({status:'awaiting-signature',preview:evmPreview('cross-device'),requestId:'same-request',action:'open'});return Response.json({status:'pending'});}if(path==='/api/evm/send'){if(sendFailure)throw Error('Lost send response');if(body.retrySame){statusMode='retried';return Response.json({status:'confirmed',txHash:'0xhash'});}return Response.json({status:'pending'});}if(path.startsWith('/api/solana/status'))return Response.json({status:{confirmationStatus:'confirmed'}});if(path==='/api/solana/send')return Response.json({ok:true});throw Error('Unexpected endpoint '+path);};
const mockPlugin={name:'wallet-mocks',setup(build){build.onResolve({filter:/paybox-browser$/},()=>({path:'paybox',namespace:'mocks'}));build.onResolve({filter:/evm-math$/},()=>({path:'evm-math',namespace:'mocks'}));build.onResolve({filter:/^@solana\/web3.js$/},()=>({path:'solana',namespace:'mocks'}));build.onLoad({filter:/.*/,namespace:'mocks'},args=>({contents:args.path==='solana'?`export class Keypair{static generate(){return {publicKey:{toBase58:()=> 'position'}}}}export class VersionedTransaction{static deserialize(){return {sign:()=>{},serialize:()=>new Uint8Array([0]),signatures:[new Uint8Array([1])]}}}`:args.path==='evm-math'?`export const signedEvmTransaction=(...args)=>globalThis.__mocks.signedEvmTransaction(...args);`:`${['mountPaybox','mountWalletPicker','payboxWallet','payboxReady','requestPayboxSignature','payboxResult','signingCard','reopenPaybox','applyPayboxSignature'].map(name=>'export const '+name+'=(...args)=>globalThis.__mocks.'+name+'(...args);').join('\n')}`,loader:'js'}));}};
await build({entryPoints:['execution/browser.ts'],outfile:join(dir,'browser.mjs'),bundle:true,platform:'node',format:'esm',banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},plugins:[mockPlugin]});
const browser=await import(join(dir,'browser.mjs'));
await build({entryPoints:['execution/evm-browser.ts'],outfile:join(dir,'evm-helper.mjs'),bundle:true,platform:'node',format:'esm',plugins:[mockPlugin]});
const {canRetrySame}=await import(join(dir,'evm-helper.mjs'));
const retryOp={credentialId:'credential',requestId:'request',txHash:'hash',signedTransactionHex:'signed',preview:{operationId:'operation',previewId:'preview',owner:evmWallet.address,expiresAt:now+1000}},retryState={credentialId:'credential',requestId:'request',operationId:'operation',owner:evmWallet.address,preview:{previewId:'preview',expiresAt:now+1000},status:'awaiting-signature',txHash:null};
assert.equal(canRetrySame(retryOp,retryState,now),true);assert.equal(canRetrySame(retryOp,retryState,now+1000),false,'expired review cannot retry');for(const patch of [{credentialId:'other'},{requestId:'other'},{owner:'0x'+'22'.repeat(20)},{txHash:'different',retrySameAvailable:true}])assert.equal(canRetrySame(retryOp,{...retryState,...patch},now),false,'retry must retain wallet, request and hash');
function host(){const h=new Node();h.connected=true;roots.push(h);return h;}
function node(h,field){return h.querySelector(`[data-composer-field="${field}"]`);}
function input(h,field,value){const n=node(h,field);n.value=value;n.dispatchEvent({type:n.tagName==='SELECT'?'change':'input'});}
async function click(h,selector){const n=h.querySelector(selector);assert.ok(n,selector);return n.onclick();}
const h=host();browser.mountSolana(h,'sol-pool',false,'',{draft:{lowerPriceSol:'0.000001',upperPriceSol:'0.000002',depositMode:'sol-only'}});
node(h,'lowerPriceSol').focus();window.LPExecution.setRange('sol-pool',{lowerPriceSol:'0.0000011',upperPriceSol:'0.0000019'});assert.equal(node(h,'lowerPriceSol').value,'0.0000011','external chart updates focused visible field');
await click(h,'[data-preview]');assert.equal(requests.find(x=>x.path==='/api/solana/preview').body.lowerPriceSol,'0.0000011');
input(h,'amountSol','1');assert.equal(h.querySelector('[data-sign]'),null,'typing invalidates approval immediately');
previewDeferred={};const reviewPromise=click(h,'[data-preview]');await new Promise(resolve=>setImmediate(resolve));input(h,'upperPriceSol','0.0000021');previewDeferred.resolve();await reviewPromise;previewDeferred=null;assert.equal(h.querySelector('[data-sign]'),null,'late review response rejected after editing');
await click(h,'[data-preview]');now+=75001;for(const timer of timers)timer.fn();assert.equal(h.querySelector('[data-sign]').disabled,true,'clock expiry disables approval without requests');now-=75001;
await click(h,'[data-preview]');await click(h,'[data-sign]');assert.equal(state.readOperation(storage,'solana').requestId,'same-request');assert.match(h.querySelector('[data-review]').textContent,/Card interrupted/);assert.ok(h.querySelector('.execution-summary')||h.querySelector('[data-review]').innerHTML.includes('execution-summary'));
assert.equal(window.LPExecution.setRange('sol-pool',{lowerPriceSol:'4',upperPriceSol:'5'}),false,'approval locks chart edits');
const signCount=requests.filter(x=>x.sign).length;h.connected=false;const reload=host();browser.mountSolana(reload,'sol-pool');assert.equal(window.LPExecution.getState('sol-pool').locked,true);assert.match(reload.querySelector('[data-review]').textContent,/Saved operation/);await click(reload,'[data-recovery]');assert.equal(requests.filter(x=>x.sign).length,signCount,'reload resumes the original request without creating another');
state.removeOperation(storage,'solana',state.readOperation(storage,'solana'));reload.connected=false;
const e=host();window.mountEvm(e,{id:'evm-pool'},'open',{draft:{lowerPriceEth:'0.00001',upperPriceEth:'0.00002',amountToken:'10'}});
await click(e,'[data-preview]');let evmCalls=requests.filter(x=>x.path==='/api/evm/preview');assert.equal(evmCalls.at(-1).body.operationId,undefined,'first review creates operation');assert.match(e.querySelector('[data-review]').innerHTML,/0\.0001/);assert.match(e.querySelector('[data-review]').innerHTML,/0\.0039/,'uses simulated allocation');
await click(e,'[data-preview]');evmCalls=requests.filter(x=>x.path==='/api/evm/preview');assert.equal(evmCalls.at(-1).body.operationId,undefined,'unsigned review refresh never reuses approval operation ID');
statusMode='approval-ready';await click(e,'[data-preview]');assert.equal(requests.filter(x=>x.path==='/api/evm/preview').at(-1).body.operationId,'existing-approval','mint continuation needs fresh confirmed approval status');
statusMode='retry-ready';requestMode='success';sendFailure=true;await click(e,'[data-sign]');const send=requests.find(x=>x.path==='/api/evm/send');assert.equal(send.body.owner,evmWallet.address);assert.equal(send.body.credentialId,evmWallet.id);assert.ok(send.body.operationId);assert.equal(state.readOperation(storage,'evm').txHash,'0xhash','hash saved before uncertain HTTP send');assert.match(e.querySelector('[data-review]').textContent,/Submission needs checking/);assert.match(e.querySelector('[data-review]').innerHTML,/execution-summary/);assert.ok(e.querySelector('[data-retry-same]'),'lost first send can offer the same signed bytes once journal confirms original request');const priorSigns=requests.filter(x=>x.sign).length;sendFailure=false;await click(e,'[data-retry-same]');const retry=requests.filter(x=>x.path==='/api/evm/send').at(-1);assert.equal(retry.body.retrySame,true);assert.equal(retry.body.signedTransactionHex,send.body.signedTransactionHex);assert.equal(retry.body.operationId,send.body.operationId);assert.equal(requests.filter(x=>x.sign).length,priorSigns,'retry creates no signature request');assert.equal(state.readOperation(storage,'evm'),null,'confirmed retry clears its operation');
e.connected=false;statusMode='discovered';requestMode='pending';const cross=host();window.mountEvm(cross,{id:'cross-device'},'open');await click(cross,'[data-recovery]');assert.equal(state.readOperation(storage,'evm').requestId,'same-request','new device discovers server operation with selected granted wallet');assert.equal(requests.filter(x=>x.sign).length,signCount+1,'cross-device recovery does not create a signing request');
await build({entryPoints:['execution/paybox-browser.ts'],outfile:join(dir,'real-paybox.mjs'),bundle:true,platform:'node',mainFields:['main'],format:'esm',banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"}});
const {walletsFromCredentials}=await import(join(dir,'real-paybox.mjs'));const credentials=[{credential_id:'sol',kind:'wallet',metadata:{address:'So11111111111111111111111111111111111111112'}},{credential_id:'evm',kind:'wallet',metadata:{address:evmWallet.address}},{credential_id:'junk',kind:'wallet',metadata:{address:'not-a-wallet'}},{credential_id:'login',kind:'login',metadata:{address:evmWallet.address}}];assert.deepEqual(walletsFromCredentials(credentials,'solana').map(w=>w.id),['sol']);assert.deepEqual(walletsFromCredentials(credentials,'evm').map(w=>w.id),['evm']);
const actual=await readFile('execution/paybox-browser.ts','utf8');assert.match(actual,/serializedTransaction|applyPayboxSignature/);assert.match(actual,/data-paybox-link/,'mobile popup has visible reopen link');
globalThis.Date=originalDate;
console.log('PASS: exact draft reload, focused chart/form synchronization, late review invalidation, clock expiry, immutable review, original-request recovery, wallet-bound EVM send, fresh sequential approval, same-hash retry identity/expiry, family wallet filtering, and cross-device journal discovery');
