import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const context={URLSearchParams};vm.runInNewContext(await readFile('public/execution-link.js','utf8'),context);
const link=context.LPExecutionLink,pool='solana:HokwvDBVQrqJ2nRCZbybdqE8x35fHkKoXDBFMLNQL9Jy';
const draft={lowerPriceSol:0.000002115176350493509,upperPriceSol:0.000004859077165837944,amountSol:.5,strategy:'bid-ask',depositMode:'sol-only'};
const url=link.build(pool,draft),parsed=link.read(new URL(url,'https://example.com').search);
assert.equal(parsed.pool,pool);assert.equal(Number(parsed.draft.lowerPriceSol),draft.lowerPriceSol);assert.equal(Number(parsed.draft.upperPriceSol),draft.upperPriceSol);
assert.equal(parsed.draft.strategy,'bid-ask');assert.equal(parsed.draft.depositMode,'sol-only');assert.equal(parsed.draft.amountSol,'0.5');
assert.equal(link.read('?compose='+encodeURIComponent(pool)).draft,null,'reload reopens persisted draft without overwriting it');
for(const patch of [{lowerPriceSol:-1},{upperPriceSol:0},{amountSol:101},{amountSol:Infinity},{strategy:'<script>'},{depositMode:'sell-everything'}])assert.equal(link.build(pool,{...draft,...patch}),null);
assert.equal(link.read('?compose=https://evil.example'),null);
assert.equal(link.build('solana:<script>',draft),null);
const forward=link.chartBounds({baseAddress:'token',quoteAddress:'SOL'},'SOL',{lower:2,upper:8},'solana');
assert.equal(forward.lower,2);assert.equal(forward.upper,8);
const reverse=link.chartBounds({baseAddress:'SOL',quoteAddress:'token'},'SOL',{lower:2,upper:8},'solana');
assert.equal(reverse.lower,.125);assert.equal(reverse.upper,.5,'inverted price keeps lower and upper ordered');
assert.equal(link.chartBounds({baseAddress:'sol',quoteAddress:'token'},'SOL',{lower:2,upper:8},'solana'),null,'Solana identities are case sensitive');
assert.equal(link.chartBounds({baseAddress:'0xAb',quoteAddress:'token'},'0xab',{lower:2,upper:8},'evm').lower,.125);
assert.equal(link.chartBounds({baseAddress:'token',quoteAddress:'USD'},'SOL',{lower:2,upper:8},'solana'),null,'mismatched chart cannot draw misleading bounds');
assert.equal(link.chartBounds({baseAddress:'token',quoteAddress:'SOL'},'SOL',{lower:2,upper:1},'solana'),null);
const html=await readFile('public/index.html','utf8');
assert.doesNotMatch(html,/rawSigned|tx\/broadcast|sign plan|Leave blank for everything/,'opening no longer falls back to unbound signed bytes');
assert.match(html,/lp:execution-draft/);assert.match(html,/lp:execution-review/);assert.match(html,/lp:execution-operation/);
assert.match(html,/executionChartStage/);assert.match(html,/mountEvm/);
console.log('PASS execution range handoff: exact bounds, amount/mix/shape preservation, invalid links rejected, copied-plan entry removed');
