import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile(new URL('../public/main-pools.js',import.meta.url),'utf8');
const at=Date.parse('2026-09-30T10:00:00Z'),iso=n=>new Date(n).toISOString();
let clock=at;class ClockDate extends Date{constructor(...a){super(...(a.length?a:[clock]));}static now(){return clock;}}
const code=source.replace(/^import .*?;\n/,'').replace(/\bexport /g,'')+'\nthis.ui={currentQuote,economicQuote,economicQuoteFresh,netFor,knownFlags,safetyChips,volumeDirection,rowModel,freshnessKey,renderTable,renderCards,queryFor,rankRows,mountMainPools,dataStamp,groupStamp};';
const baseline={pool:{id:'solana:one',pair:'TEST/SOL',ageHours:48,tvlUsd:50000,feeApr:.9,fetchedAt:iso(at)},feeRates:{h1:.001,h4:.002,h12:.003,asOf:iso(at)},trend:{volume1h:100,volume4h:400,volume24h:1000,previous4h:800,previous4hAsOf:iso(at-4*3600000),historyStatus:'available',tvlChange4h:-.1,asOf:iso(at)},config:{binStep:20,baseFee:.002,dynamicFee:.0002},safety:{rpc:{status:'available',asOf:iso(at),mintAuthority:null,freezeAuthority:null,tokenProgram:'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',extensions:[],transferFeeStatus:'none',concentration:{top1Fraction:.2,top10Fraction:.6,label:'Accounts, including vaults.',holders:{status:'available',asOf:iso(at),top1Fraction:.25,top10Fraction:.8,label:'Sampled account owners; lower bounds include vaults.'}}},flags:[]},quotes:[{sizeSol:.5,mode:'dlmm',status:'quoted',buyAsOf:iso(at),sellAsOf:iso(at),asOf:iso(at),expiresAt:at+45000,roundTripCostSol:0,exitCostSol:0,economicEstimate:{costModelVersion:3,status:'available',retainedUntil:at+3600000,asOf:iso(at),dataAsOf:iso(at),markAsOf:iso(at),expiresAt:at+600000,roundTripCostSol:0,exitCostSol:0}}],nets:[1,4,12].map(h=>({sizeSol:.5,mode:'dlmm',horizonHours:h,feeWindowHours:h,status:'estimated',netFraction:h===4?0:-.001,netHourlyRate:h===4?0:-.001/h,feesCoverExitHours:0,feesCoverCostHours:0,dataAsOf:iso(at),economicPolicyAsOf:iso(at),expiresAt:at+600000,note:'Complete dated reference cost.'}))};
function setup({rows=[baseline],quotaMode='keyed',hidden=false,rateLimit=false,detailRateLimit=false,catalogue401=false,deferFirstCatalogue=false,deferFirstDetail=false}={}){
 const events={},calls=[],opened=[],timers=new Map();let timerId=0,inFlight=0,maxInFlight=0,catalogueReads=0,detailReads=0,release,releaseDetail;const gate=new Promise(resolve=>release=resolve),detailGate=new Promise(resolve=>releaseDetail=resolve);const nodes={};
 const elements=Object.fromEntries(Object.entries({size:'0.5',mode:'dlmm',sort:'net4',search:'',minTvl:'5000',minVolume4h:'',maxAge:''}).map(([name,value])=>[name,{name,value,addEventListener:(event,fn)=>events[name+':'+event]=fn}]));elements.hideFlagged={checked:false};
 const form={elements,addEventListener:(event,fn)=>events['form:'+event]=fn};for(const key of ['status','asof','results','refresh'])nodes[key]={dataset:{},textContent:'',innerHTML:'',setAttribute(){}};
 const section={hidden};const mount={dataset:{},querySelectorAll:()=>[],classList:{add(){}},querySelector:s=>s==='[data-mp-filters]'?form:nodes[s.replace(/^\[data-mp-|\]$/g,'')],closest:s=>s==='section'?section:s==='[hidden]'&&section.hidden?section:null,contains:()=>true,addEventListener:(type,fn)=>events['mount:'+type]=fn};
 class FD{constructor(form){this.entries=Object.entries(form.elements).filter(([key])=>key!=='hideFlagged').map(([key,value])=>[key,value.value]);}*[Symbol.iterator](){yield*this.entries;}}
 const doc={hidden:false,getElementById:()=>null,addEventListener:(name,fn)=>events['doc:'+name]=fn};
 class MO{constructor(fn){events.observer=fn;}observe(){}disconnect(){}}
 const addTimer=(fn,delay,repeat=false)=>{const id=++timerId;timers.set(id,{fn,due:clock+delay,repeat:repeat?delay:0});return id;};
 const ctx={URLSearchParams,Intl,Date:ClockDate,AbortController,FormData:FD,document:doc,window:{addEventListener:(name,fn)=>events['window:'+name]=fn},MutationObserver:MO,queueMicrotask,setTimeout:(fn,delay)=>addTimer(fn,delay),clearTimeout:id=>timers.delete(id),setInterval:(fn,delay)=>addTimer(fn,delay,true),clearInterval:id=>timers.delete(id),openPoolDrawer:(row,options)=>opened.push({row,options}),fetch:async(url,opts)=>{calls.push({url,opts});inFlight++;maxInFlight=Math.max(maxInFlight,inFlight);await Promise.resolve();inFlight--;const detail=url.startsWith('/api/research/pool?'),firstDetail=detail&&++detailReads===1,firstCatalogue=!detail&&++catalogueReads===1;if(!detail&&catalogue401)return {ok:false,status:401,headers:{get:()=>null},json:async()=>({error:'Owner access required'})};if(detail&&rateLimit)return {ok:false,status:429,headers:{get:()=>null},json:async()=>({error:'cooldown'})};return {ok:true,headers:{get:()=>null},json:async()=>{if(firstCatalogue&&deferFirstCatalogue)await gate;if(firstDetail&&deferFirstDetail)await detailGate;const id=new URL('https://example.test'+url).searchParams.get('id');return detail?{pool:{id,pair:'Warm detail '+id},quotes:detailRateLimit?[{status:'rate-limited'}]:[]}:({pools:structuredClone(rows),quotesConfigured:true,quotaMode,asOf:iso(at+1000),updatedAt:iso(at),...(firstCatalogue&&deferFirstCatalogue?{pools:rows.map(r=>({...r,pool:{...r.pool,pair:'Delayed outdated row'}}))}:{})})}};}};
 vm.runInNewContext(code,ctx);return {ctx,ui:ctx.ui,mount,form,nodes,events,calls,opened,section,release,releaseDetail,async advance(ms){const target=clock+ms;while(true){const next=[...timers].filter(([,t])=>t.due<=target).sort((a,b)=>a[1].due-b[1].due)[0];if(!next)break;const [id,t]=next;clock=t.due;if(t.repeat)t.due+=t.repeat;else timers.delete(id);t.fn();await flush();}clock=target;await flush();},get maxInFlight(){return maxInFlight;}};
}
const {ui}=setup();
assert(ui.currentQuote(baseline.quotes[0],at));assert(!ui.currentQuote({...baseline.quotes[0],buyAsOf:iso(at-45001)},at));assert(!ui.currentQuote({...baseline.quotes[0],sellAsOf:iso(at+1)},at));
assert.equal(ui.netFor(baseline,.5,'dlmm',4,at).net,0);assert.equal(ui.netFor(baseline,.5,'dlmm',4,at).exitHours,0);assert.equal(ui.netFor(baseline,1,'best',4,at).net,null);
assert.equal(ui.netFor(baseline,.5,'dlmm',4,at+45001).kind,'cached');assert.equal(ui.netFor(baseline,.5,'dlmm',4,at+600000).kind,'unknown');
assert.equal(ui.netFor({...baseline,feeRates:{...baseline.feeRates,asOf:iso(at-600001)}},.5,'dlmm',4,at).net,null);
assert.equal(ui.volumeDirection(baseline,at).text,'↓ 50% vs prior 4h');assert.equal(ui.volumeDirection({...baseline,trend:{...baseline.trend,previous4h:null}},at).text,'Prior 4h unavailable');assert.equal(ui.volumeDirection({...baseline,trend:{...baseline.trend,previous4hAsOf:iso(at-1000)}},at).text,'Prior 4h unavailable');
const freshBadge=/<span class="mp-chip mp-neutral"[^>]*>Fresh<\/span>/,decayBadge=/<span class="mp-chip mp-decay"[^>]*>Decay<\/span>/;
for(const render of [ui.renderTable,ui.renderCards]){
 for(const missing of [undefined,null,NaN,Infinity]){
  const incomplete={...baseline,pool:{...baseline.pool,tvlUsd:missing,ageHours:missing,feeApr:missing},feeRates:{h1:missing,h4:missing,h12:missing},config:{binStep:missing,baseFee:missing,dynamicFee:missing},trend:{volume1h:missing,volume4h:missing,volume24h:missing},quotes:[],nets:[],safety:{status:'unknown',flags:[]}};
  const visible=render([incomplete],.5,'dlmm',at).replace(/<[^>]*>/g,' ');
  assert.doesNotMatch(visible,/\b(?:unknown|NaN|Infinity)\b/i,'missing or invalid metrics have readable labels rather than raw status/number placeholders');
  assert.match(visible,/unavailable/i);
 }

 for(const ageHours of [0,2,23.999])assert.match(render([{...baseline,pool:{...baseline.pool,ageHours}}],.5,'dlmm',at),freshBadge,'finite nonnegative age under24h receives a neutral Fresh badge');
 for(const ageHours of [24,48,null,undefined,-1,NaN,Infinity])assert.doesNotMatch(render([{...baseline,pool:{...baseline.pool,ageHours}}],.5,'dlmm',at),freshBadge,'established or invalid/unknown age must not receive Fresh');
 assert.match(render([baseline],.5,'dlmm',at),decayBadge,'valid declining prior4h comparison gets visible Decay chip');
 assert.match(render([{...baseline,trend:{...baseline.trend,volume4h:0}}],.5,'dlmm',at),decayBadge,'decline from a positive baseline to measured zero is decay');
 for(const trend of [{previous4h:null},{previous4h:0},{previous4h:400},{previous4h:200},{historyStatus:'warming'},{previous4hAsOf:iso(at-1000)},{asOf:iso(at-600001)}])assert.doesNotMatch(render([{...baseline,trend:{...baseline.trend,...trend}}],.5,'dlmm',at),decayBadge,'unknown, zero-baseline, flat or rising comparisons must not receive Decay');
}
assert.match(ui.safetyChips(baseline,at),/Largest sampled owner ≥25%/);assert.match(ui.safetyChips(baseline,at),/Top 10 sampled owners ≥80%/);assert.match(ui.safetyChips(baseline,at+300001),/Mint checks not verified/);assert.doesNotMatch(ui.safetyChips(baseline,at+300001),/Mint off/);
const unsafe=structuredClone(baseline);unsafe.pool.pair='<img src=x onerror=evil()>"';unsafe.pool.id='x" onclick="bad';unsafe.safety.rpc.mintAuthority='active';unsafe.safety.flags=[{source:'RPC',asOf:iso(at),code:'mint-authority',severity:'attention',label:'<script>oops</script>'}];
const table=ui.renderTable([unsafe],.5,'dlmm',at);assert(!table.includes('<img'));assert(!table.includes('<script>'));assert(table.includes('&lt;img'));assert(table.indexOf('Fees cover exit')<table.indexOf('Fees · 1h'));assert.equal((table.match(/scope="col" title=/g)||[]).length,11);assert.match(table,/class="mp-neutral" title="Annualised/);
assert.match(ui.renderCards([baseline],.5,'dlmm',at),/<article class="mp-card" data-main-pool=/);assert.match(ui.renderCards([baseline],.5,'dlmm',at),/0.5 SOL/);
assert.equal(ui.rankRows([unsafe,baseline],{hideFlagged:true,size:'.5',mode:'dlmm',sort:'net4'},at).length,1);
assert.equal(ui.rankRows([{...baseline,pool:{...baseline.pool,id:'unknown'},quotes:[]},{...baseline,pool:{...baseline.pool,id:'negative'},nets:baseline.nets.map(n=>({...n,netFraction:-.1,netHourlyRate:-.025}))}],{size:'.5',mode:'dlmm',sort:'net4'},at)[0].pool.id,'negative');
assert.equal(ui.queryFor({size:'.5',mode:'dlmm',sort:'net12',hideFlagged:true,minTvl:5000}).get('size'),'1');assert.equal(ui.queryFor({size:'0.5',mode:'dlmm',sort:'net12',hideFlagged:true,minTvl:5000}).get('feeWindow'),'12');assert.equal(ui.queryFor({size:'0.5',mode:'dlmm',sort:'net12',hideFlagged:true,minTvl:5000}).get('hideFlagged'),'1');
assert.equal(ui.dataStamp(iso(at)),'Data as of 10:00 UTC');assert.equal(ui.groupStamp([{pool:{fetchedAt:iso(at)}},{pool:{fetchedAt:iso(at-300000)}},{pool:{}}]).asOf,iso(at-300000));assert.equal(ui.groupStamp([{pool:{}}]).undated,1);
assert.doesNotMatch(source,/localStorage|sessionStorage|x-terminal-key|Authorization/,'Catalogue must never persist or forward an owner key');
const flush=async()=>{for(let i=0;i<50;i++)await Promise.resolve();};
const rows=[0,1,2,3,4].map(i=>({...structuredClone(baseline),pool:{...baseline.pool,id:'solana:pool'+i,ageHours:i===0?2:i===1?null:48},feeRates:{...baseline.feeRates,h4:i===0?.1:baseline.feeRates.h4},quotes:[],nets:[]}));
const hidden=setup({rows,hidden:true});hidden.ui.mountMainPools(hidden.mount);await flush();assert.equal(hidden.calls.filter(c=>c.url.startsWith('/api/research/pool?')).length,0);
const details=fixture=>fixture.calls.filter(c=>c.url.startsWith('/api/research/pool?'));
// Public quota is reserved for deliberate drawer/purchase actions: no automatic
// warm on initial load, polling, refresh, address search, or visibility changes.
clock=at;const publicMode=setup({rows,quotaMode:'public'}),publicControl=publicMode.ui.mountMainPools(publicMode.mount);await flush();assert.equal(details(publicMode).length,0);assert.match(publicMode.nodes.status.textContent,/Open a pool to check costs/);await publicMode.advance(600001);await publicControl.load(true);await flush();publicMode.form.elements.search.value='So11111111111111111111111111111111111111112';publicMode.events['form:submit']({preventDefault(){}});await flush();publicMode.events['doc:visibilitychange']();await flush();assert.equal(details(publicMode).length,0,'public mode never auto-consumes shared quote quota');assert.equal(publicControl.rows().length,rows.length,'quota mode does not discard catalogue rows');publicMode.events['mount:click']({target:{closest:()=>({dataset:{mainPool:'solana:pool0'}})}});assert.equal(publicMode.opened.length,1,'the deliberate pre-flight drawer remains available');assert.equal(publicMode.opened[0].options.sizeSol,.5);assert.equal(publicMode.opened[0].options.mode,'dlmm');
clock=at;const missingMode=setup({rows,quotaMode:null});missingMode.ui.mountMainPools(missingMode.mount);await flush();assert.equal(details(missingMode).length,0,'unadvertised quota mode fails closed for background warming');
clock=at;
const live=setup({rows});const control=live.ui.mountMainPools(live.mount);await flush();assert.equal(details(live).length,1,'the first pool is warmed immediately');assert.match(live.nodes.results.innerHTML,/Warm detail solana:pool1/,'each returned detail renders immediately');
await live.advance(19999);assert.equal(details(live).length,1,'a second pool cannot start before twenty seconds');await live.advance(1);assert.equal(details(live).length,2);
await live.advance(40000);assert.equal(details(live).length,4);assert.equal(live.calls.filter(c=>c.url.startsWith('/api/research/pools?')).length,1,'sixty-second polling cannot abort an active wave');
await live.advance(20000);assert.equal(details(live).length,5);assert.equal(live.maxInFlight,1);assert.deepEqual(details(live).map(c=>new URL('https://test.invalid'+c.url).searchParams.get('id')),['solana:pool1','solana:pool2','solana:pool3','solana:pool4','solana:pool0'],'warm displayed established/unknown rows before the separate Fresh group');assert(live.calls.every(c=>c.opts.method==='GET'));await control.load(true);await flush();assert.equal(details(live).length,5,'refresh shares the same ten-minute pool allowance');
assert.match(live.nodes.asof.textContent,/^Data as of 10:00 UTC · Solana \/ Meteora/);assert.match(live.nodes.results.innerHTML,/New pool/);assert.match(live.nodes.results.innerHTML,/Read 30 Sept|Read 30 Sep/);assert.equal(live.mount.dataset.publicLayout,'cards');assert.doesNotMatch(live.nodes.results.innerHTML,/<table/);
live.events['mount:click']({target:{closest:selector=>selector==='[data-mp-layout]'?{dataset:{mpLayout:'table'}}:null}});assert.equal(live.mount.dataset.publicLayout,'table');assert.match(live.nodes.results.innerHTML,/Fresh pools · under 24h/);assert.match(live.nodes.results.innerHTML,/Established pools & unverified ages/);assert.match(live.nodes.results.innerHTML,/<table/);
live.events['mount:click']({target:{closest:()=>({dataset:{mainPool:'solana:pool0'}})}});assert.equal(live.opened[0].options.sizeSol,.5);assert.equal(live.opened[0].options.mode,'dlmm');
live.events['doc:lp:main-pool-data']({detail:{...baseline,pool:{...baseline.pool,id:'solana:pool0',pair:'Updated from drawer'}}});assert.match(live.nodes.results.innerHTML,/Updated from drawer/);
clock=at;const throttled=setup({rows,rateLimit:true});throttled.ui.mountMainPools(throttled.mount);await flush();assert.equal(details(throttled).length,1);assert.match(throttled.nodes.status.textContent,/cooling down/);await throttled.advance(20000);assert.equal(details(throttled).length,1);
clock=at;const sharedThrottled=setup({rows,detailRateLimit:true});sharedThrottled.ui.mountMainPools(sharedThrottled.mount);await flush();assert.equal(details(sharedThrottled).length,1);assert.match(sharedThrottled.nodes.status.textContent,/Cost provider cooling down/);assert.match(sharedThrottled.nodes.results.innerHTML,/Warm detail/,'dated retained details render even when shared quoting is denied');
clock=at;const unauthorized=setup({catalogue401:true});unauthorized.ui.mountMainPools(unauthorized.mount);await flush();assert.equal(unauthorized.calls.length,1);assert.match(unauthorized.nodes.status.textContent,/Refresh failed/);assert(unauthorized.calls.every(c=>c.opts.method==='GET'&&c.opts.credentials==='same-origin'&&!c.opts.headers));
const raced=setup({rows,deferFirstCatalogue:true});const racedControl=raced.ui.mountMainPools(raced.mount);await flush();await racedControl.load(false);await flush();raced.release();await flush();assert.doesNotMatch(raced.nodes.results.innerHTML,/Delayed outdated row/);assert.equal(raced.calls.length,2,'an obsolete catalogue cannot start warming');
const detailRace=setup({rows,deferFirstDetail:true}),detailControl=detailRace.ui.mountMainPools(detailRace.mount);await flush();await detailControl.load(false);assert.equal(details(detailRace)[0].opts.signal.aborted,true,'superseded warm fetches are cancelled');detailRace.releaseDetail();await flush();assert.doesNotMatch(detailRace.nodes.results.innerHTML,/Warm detail/,'an obsolete pool detail cannot mutate a newer catalogue');
const cancelled=setup({rows});cancelled.ui.mountMainPools(cancelled.mount);await flush();cancelled.events['window:pagehide']();assert.equal(details(cancelled)[0].opts.signal.aborted,true);await cancelled.advance(20000);assert.equal(details(cancelled).length,1,'pagehide cancels the pending stagger');
clock=at;const hiddenDuring=setup({rows});hiddenDuring.ui.mountMainPools(hiddenDuring.mount);await flush();hiddenDuring.ctx.document.hidden=true;hiddenDuring.events['doc:visibilitychange']();await hiddenDuring.advance(20000);assert.equal(details(hiddenDuring).length,1,'hidden tabs cannot continue staggered quoting');
clock=at;const many=Array.from({length:35},(_,i)=>({...structuredClone(rows[2]),pool:{...rows[2].pool,id:'solana:wide'+String(i).padStart(2,'0')}})),wide=setup({rows:many}),wideControl=wide.ui.mountMainPools(wide.mount);await flush();assert.equal((wide.nodes.results.innerHTML.match(/class="mp-discovery-card"/g)||[]).length,12,'default overview displays twelve cards');assert.match(wide.nodes.results.innerHTML,/Showing 12 of 35 pools/);const readsBeforeMore=wide.calls.length;wide.events['mount:click']({target:{closest:selector=>selector==='[data-mp-more]'?{dataset:{mpMore:''}}:null}});assert.equal((wide.nodes.results.innerHTML.match(/class="mp-discovery-card"/g)||[]).length,24);assert.equal(wide.calls.length,readsBeforeMore,'pagination only reveals saved rows, without changing the read budget');await wide.advance(580000);assert.equal(details(wide).length,30,'the whole ten-minute wave has at most thirty pool reads');assert.equal(wide.maxInFlight,1);await wideControl.load(true);await flush();assert.equal(details(wide).length,30,'manual refresh cannot evade the thirty-pool bound');clock=at+600001;await wideControl.load(true);await flush();assert.equal(details(wide).length,31,'a new bounded wave can start once ten minutes have elapsed');
clock=at;const paginated=setup({rows:many,hidden:true});paginated.ui.mountMainPools(paginated.mount);await flush();paginated.events['mount:click']({target:{closest:selector=>selector==='[data-mp-more]'?{dataset:{mpMore:''}}:null}});assert.equal((paginated.nodes.results.innerHTML.match(/class="mp-discovery-card"/g)||[]).length,24);paginated.events['form:submit']({preventDefault(){}});await flush();assert.equal((paginated.nodes.results.innerHTML.match(/class="mp-discovery-card"/g)||[]).length,12,'a new filter search resets pagination');
clock=at;const freshTop=Array.from({length:31},(_,i)=>({...structuredClone(baseline),pool:{...baseline.pool,id:'solana:fresh'+String(i).padStart(2,'0')},...(i===30?{quotes:[],nets:[]}: {})})),topOnly=setup({rows:freshTop});topOnly.ui.mountMainPools(topOnly.mount);await flush();assert.equal(details(topOnly).length,0,'the top thirty are selected before filtering fresh quotes, so row31 is not silently quoted');
const retained=structuredClone(baseline);retained.pool.fetchedAt=iso(at+20*60000);retained.feeRates.asOf=iso(at+20*60000);retained.quotes[0].status='stale';retained.quotes[0].economicEstimate.status='stale';retained.nets=retained.nets.map(n=>({...n,expiresAt:at+30*60000}));clock=at+20*60000;assert.equal(ui.netFor(retained,.5,'dlmm',4,clock).kind,'retained');assert.match(ui.renderCards([retained],.5,'dlmm',clock),/Last good · ≤60m/);assert.match(ui.renderCards([retained],.5,'dlmm',clock),/30 Sept|30 Sep/,'the last good estimate keeps its original date');const retainedWarm=setup({rows:[retained]});retainedWarm.ui.mountMainPools(retainedWarm.mount);await flush();assert.equal(details(retainedWarm).length,1,'a usable twenty-minute retained estimate is still due for a fresh quote');assert.equal(ui.economicQuote(retained.quotes[0],at+60*60000),false);assert.equal(ui.economicQuote({...retained.quotes[0],economicEstimate:{...retained.quotes[0].economicEstimate,costModelVersion:2}},clock),false,'previous cost models are excluded');
console.log('Main pools passed: dated sixty-minute cost retention, ten-minute refresh, public on-demand-only checks, keyed incremental details, twenty-second stagger, thirty-pool bound, shared429 stop, poll continuity, cancellation/races, authority expiry and key privacy.');
