import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const dir=await mkdtemp(join(tmpdir(),'lp-manual-ui-'));
for(const [name,path]of [['range','src/research-range.ts'],['position','src/research-position.ts']])await build({entryPoints:[path],bundle:true,platform:'node',format:'cjs',outfile:join(dir,name+'.cjs')});
const require=createRequire(import.meta.url),math=require(join(dir,'range.cjs')),rules=require(join(dir,'position.cjs'));
const source=(await readFile('public/research-manual.js','utf8')).replace(/^import[^\n]+\n/gm,'').replace(/^export /gm,'');
const now=Date.parse('2026-09-30T12:00:00Z');
class FixedDate extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
const local=date=>{const pad=n=>String(n).padStart(2,'0');return date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate())+'T'+pad(date.getHours())+':'+pad(date.getMinutes());};
const host={innerHTML:''},result={innerHTML:''},storage={textContent:''};
const form={values:{lower:'.0008',upper:'.00099',size:'.5',entryAt:local(new Date(now-2*3_600_000)),entryPrice:'.001',entryTvl:'100000',shape:'Spot',sided:'one',minVolume:'80000',resetVolume:'150000',tvlFall:'40',maxHold:'24'},onsubmit:null};
const nodes=new Map([['researchManualCheck',host],['researchManualResult',result],['researchManualStorage',storage],['researchManualForm',form]]);
const saved=new Map(),events=new Map();let failRead=false,failWrite=false;
const context={...math,...rules,Date:FixedDate,Intl,console,document:{getElementById:id=>nodes.get(id),addEventListener:(event,fn)=>events.set(event,fn)},window:{},localStorage:{getItem:key=>{if(failRead)throw Error('blocked');return saved.get(key)??null;},setItem:(key,value)=>{if(failWrite)throw Error('quota');saved.set(key,value);}},FormData:class{constructor(form){this.form=form;}get(key){return this.form.values[key]??null;}}};
vm.runInNewContext(source+'\nglobalThis.manualUI={estimateManualInventory,renderManual,calculateManual,loadSaved,storageKey};',context);
const ui=context.manualUI;
const row={pool:{id:'solana:pool-a',pair:'TEST/SOL',fetchedAt:new Date(now).toISOString(),tvlUsd:100000,base:{address:'token'}},priceSol:.0009,
  config:{binStep:100},trend:{asOf:new Date(now).toISOString(),volume4h:200000},feeRates:{asOf:new Date(now).toISOString(),h1:.001,h4:.1}};
const near=(a,b,msg)=>assert.ok(Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(a),Math.abs(b)),`${msg}: ${a} vs ${b}`);

// Arbitrary actual bounds are not replaced with a mirrored range template.
const input={lowerPriceSol:.00073,upperPriceSol:.00097,entryPriceSol:.001,sizeSol:.5,binStep:100,shape:'Spot',oneSided:true,currentPriceSol:.0009};
const split=ui.estimateManualInventory(input);
assert.equal(split.modelUpperPriceSol,input.upperPriceSol);
assert.ok(split.modelLowerPriceSol<=input.lowerPriceSol);
assert.ok(split.modelLowerPriceSol*1.01>input.lowerPriceSol,'outward lower rounding is at most one bin');
near(split.bins.reduce((s,b)=>s+b.sol,0),.5,'SOL-only starts entirely SOL');
assert.equal(split.bins.reduce((s,b)=>s+b.token,0),0);
assert.ok(split.sol>0&&split.tokens>0,'current price inside ladder yields mixed estimated inventory');
assert.match(split.note,/Actual bin IDs, deposit weights and partial active-bin fills are unavailable/);
const down=ui.estimateManualInventory({...input,currentPriceSol:.0005});
assert.equal(down.sol,0);assert.ok(down.tokens>0);
const up=ui.estimateManualInventory({...input,currentPriceSol:.0011});
near(up.sol,.5,'above range stays SOL');assert.equal(up.tokens,0);
const mixed=ui.estimateManualInventory({...input,lowerPriceSol:.0007,upperPriceSol:.0013,oneSided:false});
near(mixed.bins.reduce((s,b)=>s+b.sol,0),.25,'two-sided starts half SOL');
near(mixed.bins.reduce((s,b)=>s+b.token,0)*input.entryPriceSol,.25,'token half valued at entry price');
const inverted=ui.estimateManualInventory({...input,solIsBase:true});
near(inverted.valueSol,split.valueSol,'canonical SOL/token price makes native orientation irrelevant');
const single=ui.estimateManualInventory({...input,lowerPriceSol:.0009,upperPriceSol:.0009,currentPriceSol:.0009});
assert.equal(single.binCount,1,'equal ordered bounds describe one bin');
assert.equal(single.modelLowerPriceSol,.0009);
assert.equal(single.modelUpperPriceSol,.0009);
assert.equal(single.sol,0,'exact bin price uses the conservative full-token boundary');
near(single.tokens,.5/.0009,'single-bin conversion at its own fixed price');
near(single.valueSol,.5,'single-bin value conserved at conversion price');
const singleUp=ui.estimateManualInventory({...input,lowerPriceSol:.0009,upperPriceSol:.0009,currentPriceSol:.001});
near(singleUp.sol,.5,'single-bin bid remains all SOL above its price');
assert.equal(singleUp.tokens,0);
const activeSingle=ui.estimateManualInventory({...input,lowerPriceSol:.001,upperPriceSol:.001,currentPriceSol:.001,oneSided:false});
assert.equal(activeSingle.binCount,1);
near(activeSingle.bins[0].sol,.25,'one active bin can hold half initial SOL');
near(activeSingle.bins[0].token*.001,.25,'one active bin can hold half initial token value');
assert.match(activeSingle.note,/partial active-bin fills are unavailable/);
assert.throws(()=>ui.estimateManualInventory({...input,entryPriceSol:.0009}),/whole entered range below/);
assert.throws(()=>ui.estimateManualInventory({...input,oneSided:false}),/entry price inside/);
assert.throws(()=>ui.estimateManualInventory({...input,lowerPriceSol:1e-15}),/1,400/);

ui.renderManual(row);
assert.match(host.innerHTML,/SOL per paired token/);
assert.match(host.innerHTML,/Current TVL is not substituted|current TVL is not substituted/);
assert.match(host.innerHTML,/device local time/);
ui.renderManual({...row,pool:{...row.pool,base:{address:'So11111111111111111111111111111111111111112'}}});
assert.match(host.innerHTML,/lower SOL\/token = 1 ÷ Meteora top/);
assert.ok(typeof form.onsubmit==='function');
let checked=ui.calculateManual(row,form);
assert.equal(checked.checked.call,'KEEP');
assert.equal(checked.position.lowerPriceSol,.0008);
assert.equal(checked.position.upperPriceSol,.00099);
assert.ok(checked.split.sol>0&&checked.split.tokens>0);
near(checked.checked.estimatedFeesSol,.5*.001*checked.checked.holdHours,'1h pace times whole hold is only a labelled scenario');
assert.match(result.innerHTML,/Actual position fees: unavailable/);
assert.match(result.innerHTML,/current-pace scenario/);
assert.match(result.innerHTML,/Actual SOL\/token balance: unavailable/);
assert.match(result.innerHTML,/Value excludes fees, taxes and exit\/network costs/);
assert.doesNotMatch(result.innerHTML,/NaN|Infinity/);
assert.match(storage.textContent,/Saved only on this device/);
const key=ui.storageKey(row);assert.ok(saved.has(key));
assert.equal(JSON.parse(saved.get(key)).values.entryAt,form.values.entryAt);
assert.equal(ui.loadSaved(row).value.lower,'.0008');
const other={...row,pool:{...row.pool,id:'solana:pool-b'}};
assert.equal(ui.loadSaved(other).value,null,'per-pool isolation');
form.values.lower='.0009';form.values.upper='.0009';
checked=ui.calculateManual(row,form);
assert.equal(checked.checked.call,'KEEP','equal actual range remains usable by rules');
assert.equal(checked.split.binCount,1);
checked=ui.calculateManual({...row,priceSol:.00089},form);
assert.equal(checked.checked.call,'WITHDRAW','price below single-bin boundary triggers exit');
checked=ui.calculateManual({...row,priceSol:.00091},form);
assert.equal(checked.checked.call,'RESET','price above single-bin boundary uses reset-volume rule');
form.values.lower='.0008';form.values.upper='.00099';

// Zero volume and 40% TVL collapse trigger withdrawal; above range has a
// separate reset activity threshold. Rules remain independent of split gaps.
checked=ui.calculateManual({...row,trend:{...row.trend,volume4h:0}},form);
assert.equal(checked.checked.call,'WITHDRAW');
assert.match(result.innerHTML,/Four-hour volume below/);
assert.match(result.innerHTML,/Triggered/);
checked=ui.calculateManual({...row,pool:{...row.pool,tvlUsd:60000}},form);
assert.equal(checked.checked.call,'WITHDRAW');
near(checked.checked.tvlChange,-.4,'exact TVL fall');
checked=ui.calculateManual({...row,priceSol:.0011},form);
assert.equal(checked.checked.call,'RESET');
checked=ui.calculateManual({...row,priceSol:.0011,trend:{...row.trend,volume4h:100000}},form);
assert.equal(checked.checked.call,'WITHDRAW');
form.values.entryPrice='';checked=ui.calculateManual(row,form);
assert.equal(checked.checked.call,'KEEP','unknown entry price affects split, not valid market rules');
assert.equal(checked.split,null);assert.match(result.innerHTML,/Inventory split unavailable/);
form.values.entryPrice='.001';form.values.entryTvl='';checked=ui.calculateManual(row,form);
assert.equal(checked.checked.call,'UNAVAILABLE');
assert.match(result.innerHTML,/Entry\/current TVL is missing/);
form.values.entryTvl='100000';

// Source dates are checked independently for fee/volume readings. Saved
// current price is not silently a fresh range signal; clock deadlines survive.
const old=new Date(now-11*60000).toISOString();
checked=ui.calculateManual({...row,trend:{...row.trend,asOf:old}},form);
assert.equal(checked.observation.volume4h,null);
assert.equal(checked.checked.call,'UNAVAILABLE');
checked=ui.calculateManual({...row,pool:{...row.pool,fetchedAt:old},priceSol:.0001},form);
assert.equal(checked.observation.priceSol,null);
assert.equal(checked.checked.call,'UNAVAILABLE');
assert.equal(checked.checked.rangeState,'unknown');assert.match(result.innerHTML,/Not verified/);assert.doesNotMatch(result.innerHTML.replace(/<[^>]*>/g,' '),/\bunknown\b/i,'internal unavailable range state is mapped to visible copy');
assert.match(result.innerHTML,/fresh current price is needed/);
form.values.maxHold='1';checked=ui.calculateManual({...row,pool:{...row.pool,fetchedAt:old}},form);
assert.equal(checked.checked.call,'WITHDRAW');
assert.match(checked.checked.reason,/Maximum hold/);
form.values.maxHold='24';
checked=ui.calculateManual({...row,feeRates:{...row.feeRates,asOf:old}},form);
assert.equal(checked.checked.estimatedFeesSol,null);
checked=ui.calculateManual({...row,feeRates:{...row.feeRates,h1:0}},form);
assert.equal(checked.checked.estimatedFeesSol,0,'observed zero pace is distinct from unavailable rate');

// Storage errors do not prevent calculations or hide that persistence failed.
failWrite=true;checked=ui.calculateManual(row,form);
assert.equal(checked.checked.call,'KEEP');assert.match(storage.textContent,/not saved/);
failWrite=false;failRead=true;
assert.match(ui.loadSaved(row).note,/storage is unavailable/);
ui.renderManual(row);assert.match(host.innerHTML,/storage is unavailable/);
failRead=false;saved.set(ui.storageKey(other),'bad json');
assert.match(ui.loadSaved(other).note,/Saved inputs were unreadable/);
const writes=saved.size;form.values.entryAt='bad';assert.equal(ui.calculateManual(row,form),null);
assert.match(result.innerHTML,/valid local entry time/);assert.equal(saved.size,writes,'invalid inputs are not persisted');
form.values.entryAt=local(new Date(now+3600000));assert.equal(ui.calculateManual(row,form),null);
assert.match(result.innerHTML,/valid past time/);
form.values.entryAt=local(new Date(now-2*3600000));form.values.minVolume='';assert.equal(ui.calculateManual(row,form),null);
assert.match(result.innerHTML,/volume, liquidity-fall and hold rules/);
form.values.minVolume='80000';
events.get('lp:research-pool')({detail:other});assert.match(host.innerHTML,/Check a real position/);
const hostile={...row,pool:{...row.pool,id:'solana:hostile',pair:'<img src=x onerror=alert(1)>'}};
ui.renderManual(hostile);ui.calculateManual(hostile,form);
assert.doesNotMatch(host.innerHTML+result.innerHTML,/<img|<script/);
assert.doesNotMatch(source,/fetch\(|sendTransaction|sendRawTransaction|Keypair|request_wallet_sign/);
console.log('PASS manual UI: arbitrary actual bounds, entry-valued split assumptions, independent fresh evidence, truthful fees/unknown balances, trigger rules, local-time inputs, per-pool persistence/failure, validation and read-only operation');
