import {poolContextSnapshot} from './fixtures/synthetic-public-data.mjs';
import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'pat-context-'));
await build({entryPoints:['src/pool-context.ts'],bundle:true,platform:'node',format:'esm',outfile:join(dir,'context.mjs')});
const {poolContext}=await import(pathToFileURL(join(dir,'context.mjs')));
const snap=structuredClone(poolContextSnapshot);
const wow=snap.pools.find(p=>p.pair==='WAVE/SOL'),gold=snap.pools.find(p=>p.pair==='GLDx/WAVE');
const c=poolContext(snap,wow.id,undefined,Date.parse('2026-09-21T00:30:00Z'));
assert.equal(c.token.address,wow.base.address);
assert.equal(c.related.length,2);assert.equal(c.related[0].pool.id,gold.id);assert.equal(c.related[0].pairedWith.symbol,'GLDx');
assert.ok(!c.related.some(x=>x.pool.pair.includes('LIKEWAVE')),'ticker substring is not identity');
assert.equal(c.related[0].stale,true,'related sources retain their own old timestamp');
assert.equal(c.related[1].stale,false);
assert.equal(poolContext(snap,wow.id,'unrelated'),null);
assert.equal(poolContext(snap,'missing'),null);
const fake={...gold,id:'fake',base:{...gold.base,address:'fake-gold'},quote:{...gold.quote,address:wow.base.address.toLowerCase()}};
assert.equal(poolContext({...snap,pools:[wow,fake]},wow.id).related.length,0,'Solana identities are case-sensitive');
assert.equal(poolContext({...snap,pools:[wow,{...gold,chain:'robinhood'}]},wow.id).related.length,0,'relations never cross chains');
const repeated=poolContext({...snap,pools:[wow,gold,gold]},wow.id);assert.equal(repeated.total,1);
const reverse=poolContext({...snap,pools:[{...wow,base:wow.quote,quote:wow.base},gold]},wow.id);assert.equal(reverse.token.address,wow.base.address,'default explores the non-cash token');
const evm={...wow,id:'robinhood:a',chain:'robinhood',base:{address:'0xABC',symbol:'A'},quote:{address:'0xDEF',symbol:'B'}};
const evm2={...evm,id:'robinhood:b',quote:{address:'0xabc',symbol:'A'},base:{address:'0x123',symbol:'C'}};
assert.equal(poolContext({...snap,pools:[evm,evm2]},evm.id,'0xabc').related.length,1,'EVM identity matching is case insensitive');
await import('../public/experience.js');const ux=globalThis.LPExperience;
assert.ok(ux.known('solana',gold.base)?.source.includes('assets.backed.fi'));
assert.equal(ux.known('solana',{...gold.base,address:'copycat'}),undefined);
assert.equal(ux.known('robinhood',gold.base),undefined);
assert.equal(ux.money(null),'—');assert.equal(ux.percent(null),'—');assert.equal(ux.money(0),'$0.00');
assert.ok(!ux.brief({...wow,activity:undefined}).includes('$0.00'),'missing window never becomes zero volume');
const hostile={...wow,base:{...wow.base,symbol:'<img src=x onerror=alert(1)>',name:'"</button>'}};
assert.ok(!ux.brief(hostile).includes('<img src=x'));assert.ok(ux.brief(hostile).includes('&lt;img'));
assert.equal(ux.miniRange({lower:1,upper:1,current:1}),'');assert.match(ux.miniRange({lower:1,upper:2,current:3}),/above/);
assert.match(ux.pulse({...wow,fetchedAt:'invalid'}).text,/Saved/);
console.log('PASS: exact-mint/chain pairings, quote orientation, source age, bounded deduplication, issuer identity, missing values and escaped token metadata');
await build({entryPoints:['src/discovery.ts'],bundle:true,platform:'node',format:'esm',outfile:join(dir,'discovery.mjs')});
const {selectPools}=await import(pathToFileURL(join(dir,'discovery.mjs')));
assert.deepEqual(selectPools(snap.pools,new URLSearchParams({watch:wow.id})).pools.map(p=>p.id),[wow.id]);
assert.equal(selectPools(snap.pools,new URLSearchParams({watch:'__empty__'})).pools.length,0);
assert.equal(selectPools(snap.pools,new URLSearchParams({watch:wow.base.address})).pools.length,0,'watchlist saves a specific pool, not every token pairing');
assert.equal(selectPools(snap.pools,new URLSearchParams({watch:wow.id,chain:'robinhood'})).pools.length,0);
console.log('PASS: watchlist selects exact pool IDs before the display limit and respects chain filters');
