import {raydiumLookup,dammCatalogue} from './fixtures/synthetic-public-data.mjs';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'lp-volume-'));
for(const [name,entry] of [['volume','src/volume.ts'],['inbox','src/range-alerts.ts'],['lookup','src/pool-lookup.ts'],['source','src/sources/meteora.ts'],['filter','src/discovery.ts']])await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',outfile:join(dir,name+'.mjs')});
const {volumeSignal,checkVolume}=await import(pathToFileURL(join(dir,'volume.mjs')));
const {selectPools}=await import(pathToFileURL(join(dir,'filter.mjs')));
const now=Date.now(),at=n=>new Date(now+n*60000).toISOString();
const p={id:'solana:pool',address:'pool',chain:'solana',venue:'meteora-dlmm',pair:'A/SOL',base:{address:'mintA',symbol:'A'},quote:{address:'sol',symbol:'SOL'},tags:[],fetchedAt:at(0),ageHours:4,priceUsd:1,tvlUsd:5000,feeApr:36.5,volume24hUsd:30000,activity:{volume30m:3000,volume1h:4000,volume4h:7000,fees1h:20}};
let s=volumeSignal(p,now);assert.equal(s.ratio,3);assert.equal(s.previous30m,1000);assert.equal(s.hourlyRatio,4);assert.equal(s.kind,'surge');
const signal=changes=>volumeSignal({...p,...changes},now);
assert.equal(signal({ageHours:.5}).ratio,null);assert.equal(signal({ageHours:.5}).kind,'new-pool');
assert.equal(signal({ageHours:null}).kind,'unavailable');assert.equal(signal({ageHours:-1}).ratio,null);
assert.equal(signal({activity:{volume30m:500,volume1h:500}}).kind,'resumed');assert.equal(signal({activity:{volume30m:500,volume1h:500}}).ratio,null);
assert.equal(signal({activity:{volume30m:3000,volume1h:2000}}).kind,'unavailable');
assert.equal(signal({activity:{volume30m:null,volume1h:4000}}).ratio,null);
assert.equal(signal({activity:{volume30m:Infinity,volume1h:4000}}).kind,'unavailable');
assert.equal(signal({activity:{volume30m:300,volume1h:400}}).kind,'steady');
assert.equal(signal({fetchedAt:at(-11)}).kind,'unavailable');assert.equal(signal({fetchedAt:at(3)}).kind,'unavailable');
const snap=(pools=[p],t=0)=>({pools,updatedAt:at(t),sources:{},errors:{}});
const first=checkVolume(snap(),null,now);assert.equal(first.events.length,1);assert.equal(first.events[0].firstObservation,true);assert.equal(first.events[0].priceChange,null);
assert.equal(checkVolume(snap(),first.state,now).events.length,0);
const next={...p,fetchedAt:at(5),priceUsd:.8,tvlUsd:4000};const second=checkVolume(snap([next],5),first.state,now+300000);assert.equal(second.events.length,0,'same burst must not spam every five minutes');
const third=checkVolume(snap([{...next,fetchedAt:at(50)}],50),second.state,now+50*60000);assert.equal(third.events.length,1);assert.equal(third.events[0].priceChange,null,'do not imply five-minute changes across a long gap');
const fourth=checkVolume(snap([{...p,fetchedAt:at(45)}],45),first.state,now+45*60000);assert.equal(fourth.events.length,1);
const stale=checkVolume(snap([{...p,fetchedAt:at(-15)}]),null,now);assert.equal(stale.events.length,0);assert.equal(stale.state.unavailablePools,1);
assert.throws(()=>checkVolume(snap([], -11),null,now));
assert.equal(checkVolume(snap([{...p,venue:'uniswap-v3'}]),null,now).events.length,0);
assert.equal(checkVolume(snap([{...p,venue:'meteora-damm-v2'}]),null,now).events.length,1);
const rising={...p,id:'second',activity:{volume30m:6000,volume1h:8000}};
assert.equal(selectPools([p,rising],new URLSearchParams('sort=volume30mUsd')).pools[0].id,'second');
assert.equal(selectPools([p,{...rising,venue:'meteora-damm-v2'}],new URLSearchParams('venue=meteora-damm-v2')).pools[0].id,'second');
assert.equal(selectPools([p,{...rising,feeApr:50}],new URLSearchParams('sort=feeApr')).pools[0].id,'second');
await import(pathToFileURL(join(process.cwd(),'public/volume-alerts.js')));
const ui=globalThis.LPVolumeAlerts;assert.equal(ui.preferences({minVolume:0,minRatio:Infinity}).minVolume,5000);assert.equal(ui.visible(first.events,ui.preferences({minRatio:4})).length,0);
assert.equal(ui.visible(checkVolume(snap([{...p,ageHours:.3}]),null,now).events,ui.preferences({newPools:false})).length,0);
// A quiet digest groups exact token identities and never sums overlapping pool volume.
const SOL='So11111111111111111111111111111111111111112',USDC='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const event=(id,base,quote,volume=8000,minutes=0)=>({...first.events[0],id,poolId:id,address:id,base,quote,pair:'SAME/SOL',at:at(minutes),signal:{...s,latest30m:volume,ratio:4},kind:'surge'});
const digest=ui.groupEvents([event('a','mint1',SOL),event('b',USDC,'mint1',12000),event('c','mint2',SOL)],ui.preferences({}),{now});
assert.equal(digest.length,2,'same ticker with a different mint stays separate');
assert.equal(digest[0].pools.length,2,'same mint across SOL and USDC is grouped despite reversed order');
assert.equal(digest[0].best.signal.latest30m,12000,'representative volume must not add multiple pools');
assert.equal(ui.groupEvents([event('a','mint1',SOL,12000,-5),event('a','mint1',SOL,1000,0)],ui.preferences({}),{now}).length,0,'latest pool observation wins before applying thresholds');
assert.equal(ui.groupEvents([event('a','mint1',SOL,8000,-121)],ui.preferences({}),{now}).length,0,'old activity leaves the main shortlist');
assert.equal(ui.groupEvents([event('a','mint1',SOL,8000,5)],ui.preferences({}),{now}).length,0,'future events are not highlights');
assert.equal(ui.groupEvents([event('a','mint1',SOL)],ui.preferences({}),{now,hidden:{'mint:mint1':now+86400000}}).length,0);
assert.equal(ui.groupEvents([event('a','mint1',SOL)],ui.preferences({}),{now,hidden:{'mint:mint1':now-1}}).length,1);
assert.notEqual(ui.tokenKey(event('a','fakeSOL','mint1')),ui.tokenKey(event('a',SOL,'mint1')),'quote identity cannot be inferred from a symbol');
const archive=ui.groupEvents([event('a','mint1',SOL,8000,-121)],ui.preferences({}),{now,maxAgeMs:Infinity});assert.equal(archive.length,1,'old activity remains browseable');
const {RangeInbox}=await import(pathToFileURL(join(dir,'inbox.mjs')));
const storage=new Map();const ctx={storage:{get:async k=>storage.get(k),put:async(k,v)=>storage.set(k,v)},blockConcurrencyWhile:async f=>f()};
const inbox=new RangeInbox(ctx);
await inbox.fetch(new Request('https://test/volume',{method:'POST',body:JSON.stringify(snap())}));
let read=await (await inbox.fetch(new Request('https://test/volume'))).json();assert.equal(read.events.length,1);assert.equal(read.state.pools,undefined,'dedup internals stay on server');
assert.equal((await (await inbox.fetch(new Request('https://test/state'))).json()).events.length,0,'volume must not overwrite range history');
await inbox.fetch(new Request('https://test/volume',{method:'POST',body:JSON.stringify(snap())}));read=await (await inbox.fetch(new Request('https://test/volume'))).json();assert.equal(read.events.length,1);
const original=globalThis.fetch,respond=d=>new Response(JSON.stringify(d));
try{
 const {lookupPool}=await import(pathToFileURL(join(dir,'lookup.mjs')));
 const fixture=structuredClone(raydiumLookup);
 const address=fixture.data[0].id,program=fixture.data[0].programId;
 globalThis.fetch=async url=>respond(String(url).includes('raydium')?fixture:{result:{value:{owner:program}}});
 const result=await lookupPool(address,'https://rpc');assert.equal(result.type,'Raydium CPMM');assert.equal(result.tokens[1].symbol,'TEST');assert.equal(result.tokens[1].transferFee,true);assert.match(result.explanation,/no personal price ranges/);
 globalThis.fetch=async()=>respond({result:{value:{owner:'TokenProgram'}}});await assert.rejects(()=>lookupPool(address,'https://rpc'),/not owned/);
 globalThis.fetch=async url=>respond(String(url).includes('raydium')?{data:[{...fixture.data[0],id:'foreign'}]}:{result:{value:{owner:program}}});await assert.rejects(()=>lookupPool(address,'https://rpc'),/not indexed/);
 const {fetchMeteora}=await import(pathToFileURL(join(dir,'source.mjs')));
 const raw=dammCatalogue;
 const urls=[];globalThis.fetch=async url=>{urls.push(new URL(url));return respond(raw);};
 const source=await fetchMeteora('meteora-damm-v2');assert.equal(source.partial,false);assert.equal(source.pools[0].venue,'meteora-damm-v2');assert.match(source.pools[0].url,/\/dammv2\//);assert.equal(source.pools[0].poolConfig.concentrated,false);assert.ok(source.pools[0].activity.volume30m>0);assert.ok(urls.every(u=>Number(u.searchParams.get('page_size'))<=100));
}finally{globalThis.fetch=original;}
// Parse the scripts as shipped, catching accidental inline syntax errors.
const html=await readFile('public/index.html','utf8');
for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())new Function(m[1]);
assert.match(html,/p\.venue === "meteora-dlmm" && window\.mountSolana/);
console.log('PASS: non-overlapping volume windows, tiny/zero baselines, young/stale/missing data, dedup, independent inbox, filters, mint identity, pool types and DAMM execution boundaries');
