import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import '../public/worldsfair.js';

const {dataUrl, filterResponse, versionLabel} = globalThis.WorldsFair;
assert.equal(globalThis.WorldsFair.showRobinhood, false, 'Reference data is off by default');
assert.equal(dataUrl('/api/pools?chain=robinhood&search=SOL',true),'/api/pools?chain=robinhood&search=SOL&includeOther=1');
for(const path of ['/api/stats','/api/long-game','/api/positions','/api/history','/api/wallet-intelligence'])assert.equal(dataUrl(path,true),path+'?includeOther=1');
assert.equal(dataUrl('/api/pools?includeOther=1&chain=solana',false),'/api/pools?chain=solana','Off always strips the other-chain opt-in');
assert.equal(dataUrl('/api/pools'),'/api/pools');
assert.equal(dataUrl('/api/solana/send',true),'/api/solana/send','The reference toggle never changes a money action');
assert.equal(dataUrl('https://other.example/api/pools',true),'https://other.example/api/pools','The toggle only affects this demo origin');
const sol = {wallet:'Sol',chain:'solana'}, rh = {wallet:'Rh',chain:'robinhood'};
const portfolio = {positions:[sol,rh],balances:[sol,rh],sources:{'positions:Sol':{label:'Meteora'},'positions:Rh':{label:'Robinhood'}},errors:{'balance:Rh':'offline'}};
const filtered = filterResponse('/api/positions?refresh=1', portfolio);
assert.deepEqual(filtered.positions,[sol]);assert.deepEqual(filtered.balances,[sol]);
assert.deepEqual(Object.keys(filtered.sources),['positions:Sol']);assert.deepEqual(filtered.errors,{});
assert.equal(portfolio.positions.length,2,'Filtering does not delete retained source data');
assert.equal(filterResponse('/api/positions',portfolio,true),portfolio,'Explicit reference toggle restores the original data');
const history={open:[sol,rh],closed:[sol,rh],robinhood:{Rh:{}},totals:{Sol:{pnl:1},Rh:{pnl:null},UnavailableRh:{note:'Robinhood token history is available below.'}},historySources:{Sol:{},Rh:{},UnavailableRh:{}},errors:{'robinhood:UnavailableRh':'offline'}};
const visibleHistory=filterResponse('/api/history',history);
assert.deepEqual(visibleHistory.closed,[sol]);assert.deepEqual(visibleHistory.open,[sol]);
assert.deepEqual(visibleHistory.totals,{Sol:{pnl:1}});assert.deepEqual(visibleHistory.historySources,{Sol:{}});assert.deepEqual(visibleHistory.errors,{});
assert.deepEqual(filterResponse('/api/pools',{pools:[sol,rh]}).pools,[sol]);
assert.deepEqual(filterResponse('/api/long-game',{items:[{chain:'Solana'},{chain:'Ethereum'},{chain:'Robinhood'}]}).items,[{chain:'Solana'}]);
assert.equal(filterResponse('/api/research/pool',portfolio),portfolio,'Unrelated research responses are unchanged');
assert.equal(versionLabel({gitSha:'a'.repeat(40),branch:'worldsfair'}),'git aaaaaaaa · worldsfair');
assert.equal(versionLabel({sourceSha:'b'.repeat(64)}),'Build identity unavailable','Source hashes are never presented as a real git commit');
assert.equal(versionLabel({gitSha:'not-a-sha'}),'Build identity unavailable');

const html=await readFile('public/index.html','utf8'),css=await readFile('public/worldsfair.css','utf8');
assert.match(html,/Paper demo · Solana/);assert.match(html,/id="worldsfairVersion"/);
assert.match(html,/url = window\.WorldsFair\.dataUrl\(url\)/);
assert.match(html,/chain: "solana"/);assert.match(html,/"settings":"alpha"/);
assert.match(html,/id="worldsfairRobinhood"/);assert.doesNotMatch(html,/id="worldsfairRobinhood"[^>]*checked/);
assert.match(html,/id="view-settings" data-robinhood-only/);
assert.match(html,/class="wallet-connection" data-mainnet-controls hidden inert/);
assert.match(css,/\[data-mainnet-controls\][^{]+\{ display:none !important; \}/);
assert.doesNotMatch(html,/<script[^>]+src="\/(?:solana|phantom|execution-link|owner-access)\.js"/,'No mainnet connection or signer script loads in the demo');
for(const script of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g))if(!/\bsrc=|\btype="module"/.test(script[1]))new vm.Script(script[2]);
const research=await readFile('public/research.html','utf8');
assert.match(research,/Paper demo · Solana/);assert.match(research,/id="worldsfairVersion"/);
assert.doesNotMatch(research,/<script[^>]+src="\/owner-access\.js"/);
console.log('PASS: Solana defaults, reversible Robinhood projection, real git footer, and inert mainnet UI');
